services:
  mysql-test-db:
    image: mysql:9.7
    container_name: mysql-test-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=db
    volumes:
      - ./db:/var/lib/mysql
      - ../test_db:/userdata:ro
